### ISSUE TITLE
Finish problem definition

### ISSUE THREAD

**Issue by svenvanhal** [svenvanhal/bachelorproject#32]

**Comment by svenvanhal** [comment]
Maybe split the Key2Soft stakeholder into separate contact persons (customer side, software side and Key2School project team) as we have to take into account their different needs.

Reflects the reality more, because sometimes even within Key2Soft opinions differ, e.g. the customer demands and the software possibilities are not compatible, and this way we can make clear in the report why we chose a certain approach for something (because even though stakeholder KS1 would like it different, we have chosen to go with the desires of stakeholder KS2 because ... etc. or found common ground or something)

**Comment by karimosman** [comment]
Agree

**Comment by karimosman** [comment]
Finished 2.1 and 2.2, you can check them. Still thinking about if we need a stakeholder map, but could be done later
