### ISSUE TITLE
Describe development methodology (See comments)

### ISSUE THREAD

**Issue by svenvanhal** [svenvanhal/bachelorproject#33]

**Comment by karimosman** [comment]
Isn't it better to add development methodology before the existing solutions?

**Comment by karimosman** [comment]
I think that the part of approach in the plan of action should be the development process. That is actually the same, and the planning would be also useful for in the report. And maybe remove plan of action from the appendix?  And maybe only adding to that testing systems that will be used, and personally i think that that part should not be large.
